[project]
name = "pydantic-provider"
version = "0.2.1"
description = "Automatically (de)serialise I/O of airflow tasks"
readme = "README.md"
authors = [
    { name = "Jacopo Nespolo", email = "jacopo.nespolo@exact-lab.it" }
]
requires-python = ">=3.11"
dependencies = [
    "apache-airflow>=3.2.2",
    "pydantic>=2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "deptry>=0.23.0",
]

[project.entry-points.apache_airflow_provider]
provider_info = "pydantic_provider.get_provider_info:get_provider_info"

[tool.deptry.package_module_name_map]
apache-airflow = "airflow"
